using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class AddSpeed : MonoBehaviour
{
    [SerializeField] private float accelerationAmount;
    public Transform airstoneTransform;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        // Player‚ÌŒ»İ‚Ìx‚¨‚æ‚ÑzÀ•W‚ğæ“¾
        float playerX = transform.position.x;
        float playerZ = transform.position.z;

        // Airstone‚Ìx‚¨‚æ‚ÑzÀ•W‚ğæ“¾
        float airstoneX = airstoneTransform.position.x;
        float airstoneZ = airstoneTransform.position.z;

        // Player‚ªCube‚Ìx‚¨‚æ‚ÑzÀ•Wã‚ğ’Ê‰ß‚µ‚½ê‡‚É‰Á‘¬‚·‚é
        if (playerX == airstoneX && playerZ == airstoneZ)
        {
            // Player‚ÌRigidbody‚ğæ“¾‚µ‚Ä‰Á‘¬‚·‚é
            Rigidbody playerRigidbody = GetComponent<Rigidbody>();
            playerRigidbody.velocity += Vector3.up * accelerationAmount;
        }
    }
}
